### ISSUE TITLE
CR - Status of all items in wishlist view

### ISSUE THREAD

**Issue by aaron-pearce** [Sam36502/WishlistFE#13]
Request status indicator per item in the overview screen showing if an item is 'reserved','received','available'

That'd be great 

**Locator**: https://www.pearcenet.ch:5000/user/aaron@aepearce.com

**Screen Shot**:
![image](https://user-images.githubusercontent.com/31019595/147498431-fbfeb657-ef55-4190-8c51-37c70b616ffe.jpeg)

**Comment by Sam36502** [comment]
Fixed by Version 1.2 ([f44245e](https://github.com/Sam36502/WishlistFE/commit/f44245e29cbe1985c4ddc86159be8e1f56bf8d3b))
